- ignore: { name: Use newtype instead of data }
- warning: { name: Use readTVarIO }
- warning: { name: Use <$> }
- warning: { name: Move brackets to avoid $ }
- warning: { name: Use let }
- ignore: { name: Use fewer LANGUAGE pragmas }