name:                habits
version:             0.1.0.0
github:              "githubuser/habits"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/habits#readme>


# Good Defaults can be found here: https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/

dependencies:
- base >= 4.7 && < 5
- text
- QuickCheck
- quickcheck-instances
- mtl
- transformers
- data-has
- lens
- monad-control
- haskus-utils-variant
- haskus-utils-types
- transformers-base
- lifted-base
- exceptions
- unliftio
- uuid
- template-haskell
- esqueleto
- async
- resourcet
- persistent
- esqueleto
- monad-logger
- persistent-postgresql
- bytestring
- resource-pool
- newtype
- vector
- first-class-families
- brittany
- singletons
- ormolu
- quickcheck-text
- haskell-src-meta
- password
- time
- jwt
- fixed
- timeit
- record-dot-preprocessor
- record-hasfield
- validation

default-extensions:
  - TypeOperators
  - InstanceSigs
  - KindSignatures
  - FlexibleContexts
  - FlexibleInstances
  - LambdaCase
  - NamedFieldPuns
  - OverloadedStrings
  - TypeApplications
  - RankNTypes
  - DataKinds
  - ScopedTypeVariables
  - MultiParamTypeClasses
  - GeneralizedNewtypeDeriving
  - FunctionalDependencies
  - TypeFamilies
  - QualifiedDo
  - TemplateHaskell
  - GADTs
  - ConstraintKinds
  - PatternSynonyms
  - PartialTypeSignatures

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wno-simplifiable-class-constraints
  - -Wno-unused-do-bind
  - -Wmissing-methods
  - -Werror=missing-fields
  - -F -pgmF=record-dot-preprocessor

library:
  source-dirs: src


executables:
  habits-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - habits

# Note
# Adding src during development here makes the ide experience much smoother. It's caused by a stack bug that leads to staleness problems when adding new files or types to the habits library
# related issues: https://github.com/haskell/haskell-language-server/issues/2058, https://github.com/haskell/haskell-language-server/issues/1822 https://github.com/haskell/haskell-language-server/issues/366
#                 https://github.com/commercialhaskell/stack/issues/5380

tests:
  habits-test-unit:
    main:                Spec.hs
    source-dirs:
    - src # Adding src, see Note above
    - test-common
    - test-unit
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - habits
    - hspec
    - hspec-expectations-lifted
    - testcontainers >= 0.3.0.1
  habits-test-integration:
    main:                Spec.hs
    source-dirs:
    - src # Adding src, see Note above
    - test-common
    - test-integration
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - habits
    - hspec
    - hspec-expectations-lifted
    - testcontainers >= 0.3.0.1
