name:                habits
version:             0.1.0.0
github:              "githubuser/habits"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/habits#readme>

dependencies:
- base >= 4.7 && < 5
- text
- QuickCheck
- quickcheck-instances
- mtl
- transformers
- data-has
- control-monad-exception
- lens
- monad-control
- haskus-utils-variant
- transformers-base
- lifted-base
- exceptions

extra-deps:
  - git: https://github.com/i-am-tom/oops.git
  - commit: 72932c6d6ebc69b086806686929fc30f20eddf74

library:
  source-dirs: src

executables:
  habits-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - habits

tests:
  habits-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - habits
    - hspec
