# Run unit tests on any branch/fork pull request
on:
  - pull_request
  - push

name: Unit tests

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: haskell/actions/setup@v1.2
      name: Setup Haskell Stack
      with:
        stack-version: 2.7.5
        ghc-version: 9.0.2
    - run: make test-unit
